### ISSUE TITLE
Merge Network interfaces

### ISSUE THREAD

**Issue by GuutBoy** [aicis/fresco#103]
Currently SCENetwork, SCENetworkSupplier and Network interfaces are all offer very similar functionality. We want to merge these making it easier to implement new networks.

**Comment by GuutBoy** [comment]
As I see it you could do everything exactly as it is done now, but it would just be gathered in a single networking interface in stead of three.

**Comment by Rhaea** [comment]
Well, true. However, the internal network strategy of how to bundle messages should imo be kept internal. It only adds to complexity to combine all interfaces - it does not make it easier. 
I see the point of making it possible to optimize a strategy when you yourself control how all communication is done. I would rather make it possible to supply your own internal network strategy than gather all interfaces as I foresee this to be very confusing for developers.
