### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by GuutBoy** [aicis/fresco#106]
The goal is 100% test coverage of the framework with prioritizing projects in the following order:
 - [x] Core 
 - [ ] Suite
 - [x] Demo
 - [x] Tools

**Comment by Rhaea** [comment]
I had, and will have a few hours to work on improving the SPDZ test coverage. Just FYI. Will not put myself as assignee or change label for that. Should we? Not sure what the best course of action is.

**Comment by GuutBoy** [comment]
I think it is a good idea to do, so we know what is going on.

**Comment by Rhaea** [comment]
Started test coverage on demo within the branch https://github.com/aicis/fresco/tree/demos-test-coverage

**Comment by GuutBoy** [comment]
I will close this to favor more specific issues.
