### ISSUE TITLE
Update the Demo project to be compatible with the new framework design

### ISSUE THREAD

**Issue by GuutBoy** [aicis/fresco#110]
The Demo's in the demo project are not up to date with the recent framework updates. This should be fixed.

EDIT: This includes using the new style of protocol creation using the ProtocolBuilder instead of the old ProtocolFactories.

**Comment by n1v0lg** [comment]
As far as the aggregation demo goes, it will need to be rewritten once https://github.com/aicis/fresco/issues/122 is done so no need to spend time on it until then.

**Comment by Rhaea** [comment]
Fixed with https://github.com/aicis/fresco/pull/123

**Comment by GuutBoy** [comment]
This issue cannot be closed yet. While demo's seem to be running now, they still need to be rewritten to follow the new framework architecture. I.e., they need to be rewritten to use the new builder system.

**Comment by Rhaea** [comment]
This is now done within #143
