### ISSUE TITLE
How to correctly implement division and floating point precision 

### ISSUE THREAD

**Issue by DaWNFoRCe** [aicis/fresco#128]
I have noticed the presence of the classes DivisionFactory and DivisionFactoryImpl. However DivisionProtocolBuilder. I was wondering whether or not this is normal, and whether or not is it possible to have either fixed or floating point arithmetic on Fresco

**Comment by GuutBoy** [comment]
I am wondering which version of FRESCO you have? I would recommend using the develop branch as that is the most up to date. The project is going through some architectural changes, and things are a little messy at the moment, sorry about that. 

Anyway, in the current direction FRESCO is going actually neither of those are relevant anymore. You can find the current implementations of division in the dk.alexandra.fresco.lib.math.integer.division package. When building protocols using division you would then use AdvancedNumericBuilder to supply the division operations (which you get from a ProtocolBuilderNumeric) ... I hope that makes sense.      

There is currently not an implementation of floating point numbers in FRESCO, btw.

**Comment by DaWNFoRCe** [comment]
Hi, Thanks so much for the quick answer. What about fixed point?

**Comment by GuutBoy** [comment]
As far as I recall, no.

**Comment by DaWNFoRCe** [comment]
Thanks!
I'm using the master branch, just did the pull just in case and I'm up-to-date. I was using it because I assume was stable. If I understand correctly the recommendation would be to use dev instead? In the master branch, what should I do?

I was wondering, about the precision though, is it recommended to use Fresco for statistical calculations? specially in the case point precision is needed? 

Best,
Abdel

**Comment by GuutBoy** [comment]
There are some basic statistical functionalities implemented, but we haven't used it very much in prototypes. So you could say those are not really stress tested. 

About floating point numbers. So far we have been able to get by with just integers. Somewhere a long the line we will probably want floating point as well, but it is not currently something we are looking in to. 

We would be happy to accept a PR adding floating point support of course.

**Comment by DaWNFoRCe** [comment]
Thanks!
I think it could be a really nice addition to the framework in general!

**Comment by GuutBoy** [comment]
You can also have a look at this project to doing linear regression with FRESCO https://github.com/Charterhouse/Fresco-Logistic-Regression . They implement fix point numbers in Kotlin.
