### ISSUE TITLE
Implement Base ROT

### ISSUE THREAD

**Issue by n1v0lg** [aicis/fresco#187]
Need an implementation of base random oblivious transfer protocol for instantiating random ot extensions.

**Comment by jot2re** [comment]
I will implement the Simplest protocol for OT by Chou and Orlandi

**Comment by GuutBoy** [comment]
@jot2re Great, not sure if you are aware, but there is an updated version of that protocol (https://eprint.iacr.org/2017/1011). If you haven't already, you should check it out as it fixes some flaws in the original protocol.

**Comment by jot2re** [comment]
Because of some things that were hard to get efficient realisations of in CC15 I implemented the Naor Pinkas OT instead.
