### ISSUE TITLE
Use SHA-256 as a PRG

### ISSUE THREAD

**Issue by jot2re** [aicis/fresco#192]
Currently we use the standard java implementation of a secure randomnessgenerator. i.e. SHA1PRNG in SecureRandom. However, this is not satisfactory as we wish to use SHA-256 instead, which already exists in MessageDigest.
Use SHa-256 from the MessageDigest class to implement a PRG based and use this all places where SHA1PRNG is used.

**Comment by Rhaea** [comment]
We already have a class called DetermSecureRandom. This currently uses SHA1 I believe, but is easily changed to SHA-256. Whether the implementation actually works as expected should be investigated. Seems like the Javadoc is faulty at least.

**Comment by GuutBoy** [comment]
@n1v0lg DetermSecureRandom is mainly a testing thing, right?

**Comment by n1v0lg** [comment]
@GuutBoy I believe that was implemented before me. I haven't used it before, so I'm not sure.

**Comment by GuutBoy** [comment]
Erh, sorry about that. I dont know why I thought you wrote it.

**Comment by GuutBoy** [comment]
Btw. if you take a look at DetermSecureRandom, it actually looks like it should be pretty easy to modify to use any hash you like.

**Comment by Rhaea** [comment]
I believe it was @tpj or myself who wrote it back in the days. The concept is still valid as far as I can see, and should be applicable to this issue. Actually, let me just take this issue myself :) - should be easy and fast to do.

**Comment by GuutBoy** [comment]
As I said should be pretty easy to do ... just expose the constructor allowing a choice of digest algorithm (which is now protected).
