### ISSUE TITLE
Implement a malicious exception super-class

### ISSUE THREAD

**Issue by jot2re** [aicis/fresco#193]
Currently there is no common strategy to signal to the user if a party has acted maliciously. This task is about creating a superclass of exceptions to indicate such a case. In the OT extension package some exceptions name Malicious*Exception already indicates malicious behaviour, these should be changed to extend such a super exception and exceptions should be thrown in the rest of the codebase when malicious behaviour is detected.

**Comment by pffrandsen** [comment]
Fixed on develop through the Mascot branch
