### ISSUE TITLE
Remove dependency on SCAPI

### ISSUE THREAD

**Issue by jot2re** [aicis/fresco#220]
Currently we use a SCAPI jar file for doing OTs in TinyTable. This seems to be a legacy thing from before we had implemented OT extension. Furthermore, it seems that this is not even an officiel release jar.
Thus we wish to remove dependency on SCAPI and use our own OT extension.
- [x] Remove SCAPI network
- [ ] Remove SCAPI OT from TinyTable

**Comment by GuutBoy** [comment]
Upgraded this to a milestone.
