### ISSUE TITLE
Allow general, non-hardcoded modulus in MiMC test

### ISSUE THREAD

**Issue by n1v0lg** [aicis/fresco#228]
Currently, one of our MiMC tests checks that encryption is deterministic by comparing the ciphertext of a fixed value and a fixed modulus against a hard-coded value. This only works for a hard-coded modulus. We should either re-implement a non-MPC version of MiMC and compare results against that, or find another way to avoid hard-coding the modulus.

**Comment by jonas-lj** [comment]
This was fixed by commit https://github.com/aicis/fresco/commit/868c4ddb886e51dd510f990089f72ca6e049bf5d which removed TestMiMCEncryptsDeterministically.
