### ISSUE TITLE
Clean up use of Drbg

### ISSUE THREAD

**Issue by n1v0lg** [aicis/fresco#231]
This consists of two small sub-issues.

- [x] We should add a default constructor to our Drbg implementations, which generate auto-generate secure, "reasonable" seeds.
- [x] We should move the Drbg from NumericResourcePool to the MascotResourcePool.

**Comment by Rhaea** [comment]
I don't think we should move it to Mascot only. It might only be used there for now, but future protocols might find it a useful class.

**Comment by GuutBoy** [comment]
In case it is useful to future protocols we can put it the resource pool for those protocols. It does not really fit well in `NumericResourcePool` as it is.

**Comment by GuutBoy** [comment]
Fixed in #238
