### ISSUE TITLE
Optimize multiplication in GF(2^k) used in OT extension 

### ISSUE THREAD

**Issue by GuutBoy** [aicis/fresco#251]
In the current OT extension implementation a large amount of time is spent computing multiplications in GF(2<sup>k</sup>) when computing inner products of vectors with entries in GF(2<sup>k</sup>). It should be possible to optimize this computation. 

The concrete method to optimize is `RotSharedImpl.multiplyWithoutReduction(...)`. 

On modern processors one could do this using the [CLMUL instruction set](https://en.wikipedia.org/wiki/CLMUL_instruction_set), however, this does not seem to be immediately available in Java.

**Comment by jot2re** [comment]
Won't work in Java without JNI. Won't fix.
