### ISSUE TITLE
Only dummy suite appears to be include in Maven releases?

### ISSUE THREAD

**Issue by elfprince13** [aicis/fresco#258]
The documentation says I can get start with FRESCO by downloading the Maven release (this resolves to http://repo1.maven.org/maven2/dk/alexandra/fresco/core/1.0.0/), which doesn't appear to contain any of the actual protocol implementations.

**Comment by n1v0lg** [comment]
Hey, in order to use a suite in your application (for instance SPDZ) you need to include it as a dependency in your pom file:

```
<dependency>
  <groupId>dk.alexandra.fresco</groupId>
  <artifactId>spdz</artifactId>
  <version>1.0.0</version>
</dependency>
```

We'll update our readthedocs page accordingly. Hope this helps!

**Comment by elfprince13** [comment]
Great thanks!
