### ISSUE TITLE
Replace SCAPI based OT's in TinyTables.

### ISSUE THREAD

**Issue by GuutBoy** [aicis/fresco#280]
We would like to get rid of the SCAPI dependency. Presumably, we would use some of the OT implementation work that was done for MASCOT.

**Comment by jot2re** [comment]
Removed SCAPI and made the implementation use the Bristol OT instead. Notice that this implementation only supports malicious security as it is only a tiny bit slower than semi-honest security. Thus, the OTs used in the TinyTable is now maliciously secure, but the rest of the TinyTable implementation is still only semi-honestly secure.
