### ISSUE TITLE
mvn test crash in spdz.TestSpdzLPBuildingBlocks

### ISSUE THREAD

**Issue by rdragos** [aicis/fresco#29]
I keep receiving this error: java.lang.OutOfMemoryError: GC overhead limit exceeded
Also I get an error in spdz.TestSpdzLPSolver2Parties: "File with filename 'spdz/SPDZ_1_2_0_EXP' not found."

Do these tests work on your build?
Thanks.

**Comment by Tophwells** [comment]
I got the same error. Not sure what it means; giving the JVM more memory didn't seem to fix it.

**Comment by GuutBoy** [comment]
This is a known error, it mainly has to do with the concrete test, so you should be able to safely ignore it though.

**Comment by GuutBoy** [comment]
... Of course it needs to be fixed so that all tests will go through, but we have not had the time lately.

**Comment by rdragos** [comment]
I can try to solve it, if that's OK with you - but I can't promise I will succeed.

**Comment by GuutBoy** [comment]
Sure, anyone is more than welcome to contribute a solution :). My intuition is that we need to tell maven somehow to give the JVM running the test more memory. However, I am not sure exactly what the problem is.

**Comment by rdragos** [comment]
I fixed it with this comment: http://stackoverflow.com/a/18771124/2404552

**Comment by GuutBoy** [comment]
Interesting, I wonder if this can be set up in the pom or similar so each user does not have to do the export.

**Comment by GuutBoy** [comment]
I found an other method to fix this. Simply add 
`<reuseForks>false</reuseForks>` 
To the configuration of the surefire plugin in the pom.xml file. This should have the test in each test class run in a separate processes. I think it is a slightly nicer fix as it does not require people to remember to export the MAVEN_OPTS. 

However, that this works might suggest there is a memory leak in some of the tests. I should look into this further.
