### ISSUE TITLE
Consistency: Let SReal extend DRes<SReal>

### ISSUE THREAD

**Issue by mvonmaltitz** [aicis/fresco#300]
Starting with the sum demo, I tried to create the same example using decimal numbers. 
Expectation: Changing SInt to SReal, numeric to realNumeric etc.  should be sufficient. 
Actual result: Compile errors like   

    method RealNumeric.add(DRes<SReal>,DRes<SReal>) is not applicable
    (argument mismatch; SReal cannot be converted to DRes<SReal>)

Analysis: 
While the interface `SInt extends DRes<SInt>`, `SReal` does not extend `DRes<SReal>`.
Changing the interface to actually extend `DRes<SReal>` fixes this error and lets my example work as expected. Especially, the currently only class which realizes `SReal` is `SFixed`. This already explicitly implements `SReal` and `DRes<SReal>`. Hence, no changes are needed here. 

Suggestion: 
Let `SReal` extend  `DRes<SReal>`

**Comment by GuutBoy** [comment]
This looks like an unintended inconsistency. Thanks a lot.

**Comment by GuutBoy** [comment]
Fixed in #301
