### ISSUE TITLE
demos-common test failing

### ISSUE THREAD

**Issue by abspoel** [aicis/fresco#329]
Freshly cloned the repository, and ran `mvn install`. I'm getting (among others) the following error on `demos-common`:

    Error while parsing arguments / instantiating protocol suite: Could not parse '1:localhost:8080:bla:toomuch' as [id]:[host]:[port]

Logs here: [demos-common.log](https://github.com/aicis/fresco/files/2779712/demos-common.log)
[surefire.log](https://github.com/aicis/fresco/files/2779714/surefire.log)

I compared it to the CI tests, but it seems the demos-common test is skipped there?

**Comment by GuutBoy** [comment]
I was just looking into this. But unfortunately I could not reproduce the error. Can you please give us the exact steps that let to this error? 

On my machine running
```
git clone https://github.com/aicis/fresco.git
cd fresco
mvn clean install
```
Ran without problems.
