### ISSUE TITLE
Does the project include conversion between arithmetic and Boolean shares？

### ISSUE THREAD

**Issue by Eleven-Z** [aicis/fresco#365]
I studied the latest Ivan Damgard research [1] and found that the interconversion between Arithmetic and Binary is already a reality and has been implemented through the Fresco framework. When will this result be integrated in the open source code, or is it already integrated in the latest version? What is that specific class of information?

[1] Damgard I , Escudero D , Frederiksen T , et al. New Primitives for Actively-Secure MPC over Rings with Applications to Private Machine Learning[C]// 2019 IEEE Symposium on Security and Privacy (SP). IEEE, 2019.

**Comment by jonas-lj** [comment]
Hi Eleven-Z, and sorry for the late reply. If I understand your question correctly, you are asking about the SPDZ2k protocol which is discussed in that paper. There is an half finished implementation of SPDZ2k in FRESCO currently, https://github.com/aicis/fresco/tree/master/suite/spdz2k, and more in the branch spdz2k-develop, but unfortunately we do not have the time to do work more on it right now.
