### ISSUE TITLE
Base NaorPinkasOT Optimization with Elliptic Curves

### ISSUE THREAD

**Issue by Gugi264** [aicis/fresco#375]
I wrote an (optional) optimization for  Naor Pinkas OT which uses elliptic curves instead of Big Integers. 
The only problem is it adds bouncy castle as a dependency.
Is this a problem? Otherwisee I could make a PR.

**Comment by jonas-lj** [comment]
That sounds good! An extra dependency is not a problem for me, especially if it's just for the OT module (is it just for that module or for core?)

**Comment by Gugi264** [comment]
The extra dependency is just for the OT module
