### ISSUE TITLE
HL17 baseOt implementation

### ISSUE THREAD

**Issue by Gugi264** [aicis/fresco#388]
Naor Pinkas is not the fastest base OT. 
By changing the protocol to [HL17 ](https://eprint.iacr.org/2017/1011) we can cut speedup the offline phase. (From 31 to 17 seconds in my tests, when using BigInteger). (In the case of Spdz with Mascot)
The HL17 is based on ChouOrland OT

**Comment by jot2re** [comment]
Hi Gugi,
Thanks a lot for your request! And sorry for the long reply time. 
I had a look at the paper you reference, HL17. While it comes from a good university, it is not yet peer reviewed and published. For this reason I reached out to Claudio Orlandi (the author of the ChouOrlandi OT) and asked about HL17. He unfortunately told me that their fix is flawed. 
Furthermore he told me that the fix suggested by https://eprint.iacr.org/2017/370.pdf Is also flawed.
Finally he told me that there **is** a fix to the ChouOrlandi OT, which is described  recently by [Abdalla et al.](https://eprint.iacr.org/2021/1218)
