### ISSUE TITLE
Fix parameters for Naor Pinkas OT

### ISSUE THREAD

**Issue by jot2re** [aicis/fresco#402]
The parameters for NaorPinkas OT does not appear to be secure. In any case there is no information about how they are derived.
There should be a test deriving these (using a secure hash function, or preferably HMAC). 
Furthermore, the modulus should be a safe prime! I.e. p=2q+1 This is not the case currently
Finally it seems that the random values are sampled module p and not mod q, where it should be the case.

Note for efficiency reasons the generator 2 could be used. In any case, it should be validated that the generator generates the entire subgroup. I.e. g^{q} mod p = 1

**Comment by jot2re** [comment]
For example consider adding the following test:
```
@Test
  public void validateParameters() {
    BigInteger subgroupSize = staticSpec.getP().subtract(BigInteger.ONE).divide(BigInteger.valueOf(2));
    assertEquals(BigInteger.ZERO,
        staticSpec.getP().subtract(BigInteger.ONE).remainder(BigInteger.valueOf(2)));
    assertTrue(subgroupSize.isProbablePrime(80));
  }
```

**Comment by Quacktiamauct** [comment]
The parameters for NoarPinkas OT seems to be defined in https://github.com/aicis/fresco/blob/87ce7366ce577f66034e7ae5db457a8d65ab3535/tools/ot/src/main/java/dk/alexandra/fresco/tools/ot/base/DhParameters.java, which is also used in ChouOrlandi based on BigIntegers.

**Comment by jot2re** [comment]
Yes, exactly. I checked the parameters and P is not a safe prime. Computing and making an automated test for validating security of the parameters, is what this task is about.

**Comment by Quacktiamauct** [comment]
But in this case, should we generate a random pair of `p` and `g` or should we switch over to a static safe pair, i.e. https://www.ietf.org/rfc/rfc3526.txt? In either case the static unsafe pair should be changed.

**Comment by Quacktiamauct** [comment]
Also, it seems like the DH parameters are tested here () actually, however it fails the sanity check for being a safe prime, as you described earlier.
https://github.com/aicis/fresco/blob/master/tools/ot/src/test/java/dk/alexandra/fresco/tools/ot/base/TestDhParameters.java

**Comment by jot2re** [comment]
Right, but it only shows the generation from a PRG seed. It does not validate the safety. (Because they are not safe).
It is crucial to _always_ use safe parameters, as otherwise the discrete log assumption might not be hard and the security of the entire system falls to the ground.
If the primes in this [standard](https://www.ietf.org/rfc/rfc3526.txt) are safe then please use them. Even better than generating them ourselves. But please verify they are safe! The standard does not mention safe or Sophie Germain (other term for safe primes)

**Comment by Quacktiamauct** [comment]
Fixed in https://github.com/aicis/fresco/pull/389/commits/2ce267e45e817b797bdeff2599c5c20f5de294c6
