### ISSUE TITLE
Extend demos with mean calculation

### ISSUE THREAD

**Issue by fnwirth** [aicis/fresco#412]
Would it be possible to add a demo demonstrating the calculation of an arithmetic mean between n-parties (while each party provides a single integer)

**Comment by quackzar** [comment]
You can use the `SampleMean` from the [fresco-stat](https://github.com/alexandrainst/fresco-stat/blob/edb0b85a73c0b665a5486d5e3a161f1f0683f85d/src/main/java/dk/alexandra/fresco/stat/descriptive/SampleMean.java) library, you can see the [unit tests](https://github.com/alexandrainst/fresco-stat/blob/eb783086339e6b752c7c60406d49a87174806055/src/test/java/dk/alexandra/fresco/stat/DescriptiveStatTests.java#L105) as an example of how to use it.
