### ISSUE TITLE
Batching communication

### ISSUE THREAD

**Issue by jimouris** [aicis/fresco#421]
Hello!

I'm looking into the code and I'm trying to understand if there is any sort of batching communication for operations that can be executed in parallel. The [MP-SPDZ paper](https://eprint.iacr.org/2020/521.pdf) mentions an example with:
```python
a = b * c
e = d * f
```
where the two multiplications can be batched together and that FRESCO is already doing it. Could you point me to the code if any such optimization has been implemented?

Thank you!

**Comment by quackzar** [comment]
I might suggest looking at the [`BatchedProtocolEvaluator`](https://github.com/aicis/fresco/blob/master/core/src/main/java/dk/alexandra/fresco/framework/sce/evaluator/BatchedProtocolEvaluator.java) or maybe [pairInPar](https://github.com/aicis/fresco/blob/24ef551966ec0846585196538a546db381c351ec/core/src/main/java/dk/alexandra/fresco/framework/builder/BuildStep.java#L95-L114) which can be used in that [way](https://github.com/aicis/fresco/blob/24ef551966ec0846585196538a546db381c351ec/demos/distance/src/main/java/dk/alexandra/fresco/demo/DistanceDemo.java#L61-L71).
