### ISSUE TITLE
GreaterThanProtocol returns opposite of what is expected.

### ISSUE THREAD

**Issue by markspanbroek** [aicis/fresco#66]
The Javadoc of ComparisonProtocolFactory.getGreaterThanProtocol() specifies that it should return 1 when x1 >= x2, and 0 otherwise. It appears to be doing the exact opposite.

**Comment by Rhaea** [comment]
Yes, this is true and known, but well spotted :) - we'll fix this soon

**Comment by Rhaea** [comment]
Fixed with https://github.com/aicis/fresco/pull/124
