### ISSUE TITLE
Cannot Property Run Quick Start Example

### ISSUE THREAD

**Issue by ssilwa** [aicis/fresco#74]
Hello, I am trying to run the quick start code here:

http://fresco.readthedocs.io/en/latest/quickstart.html

However, when I compile the file with this:

`$ javac -cp target/fresco-0.2.0-SNAPSHOT-jar-with-dependencies.jar tmp/AESDemo.java
`

I get a lot of errors like this:

`error: package dk.alexandra.fresco.framework does not exist`

I made sure to run everything from the directory that contains target folder and the tmp folder (as described in the tutorial). What am I doing wrong here? Thank you for your help!

**Comment by GuutBoy** [comment]
I think most of us are on vacation this week. But I will be happy to look into this next week.

Unfortunately, the documentation is somewhat out of date by now and this may include the QuickStart section. I am planning to fix this very soon though.

Den 12. apr. 2017 kl. 01.19 skrev Sandeep Silwal <notifications@github.com<mailto:notifications@github.com>>:


Hello, I am trying to run the quick start code here:

http://fresco.readthedocs.io/en/latest/quickstart.html

However, when I compile the file with this:

$ javac -cp target/fresco-0.2.0-SNAPSHOT-jar-with-dependencies.jar tmp/AESDemo.java

I get a lot of errors like this:

error: package dk.alexandra.fresco.framework does not exist

I made sure to run everything from the directory that contains target folder and the tmp folder (as described in the tutorial). What am I doing wrong here? Thank you for your help!

-
