### ISSUE TITLE
Where is the documentation for Fresco?

### ISSUE THREAD

**Issue by ssilwa** [aicis/fresco#77]
Hello,

I cannot find any documentation for fresco. I am looking for documentation that describe the secure functionalities of fresco and what classes they are implemented in. I cannot seem to find it in the website. Can someone please point me towards a source? For example, I am trying to find a class that securely converts a boolean value to an integer.

**Comment by ssilwa** [comment]
Bump, can someone please reply.

**Comment by GuutBoy** [comment]
Sorry for the late reply. The functionalities can be found in the lib package (see [here](https://github.com/aicis/fresco/tree/master/src/main/java/dk/alexandra/fresco/lib)). I am not sure if the functionality you are looking for is there though.
